In [1]:
import numpy as np
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [2]:
np.identity(9)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
arr=np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
np.identity(5,dtype='int16')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [10]:
arr.reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [15]:
ar2=np.arange(8).reshape(4,2)
ar2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
ar2.shape

(4, 2)

In [24]:
ar2[2:-1,0]

array([4])

In [ ]:
a

In [27]:
np.sum(ar2)

28

In [28]:
a=np.arange(44).reshape(4,11)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]])

In [31]:
np.sum(a,axis=0)

array([ 66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106])

In [35]:
np.sum(a,axis=1)

array([ 55, 176, 297, 418])

In [36]:
np.sum(a)

946

In [59]:
np.linspace(1,100,retstep=True,dtype=int)

(array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100]),
 2.020408163265306)

In [363]:
np.random.randint(1,100)

45

In [365]:
np.random.randint(1,100,7)

array([54, 78, 62, 72, 32, 61, 66])

In [367]:
np.random.rand(10)

array([0.86771778, 0.45867263, 0.48612529, 0.51595698, 0.03309949,
       0.94313218, 0.3117873 , 0.79667235, 0.97254472, 0.59179315])

In [369]:
np.random.randn(10,4)

array([[-0.18343886, -0.72137004,  0.35333317, -0.293457  ],
       [ 1.38159043,  0.99034732, -0.20760279, -1.17788387],
       [ 0.59952295, -1.52970408, -0.4908111 ,  0.01798188],
       [-0.01853342,  1.02284866, -1.84539775,  1.48467742],
       [ 0.83073894, -1.33665753,  0.85144524,  0.66058338],
       [ 0.57614264,  0.23476867,  1.0478836 , -0.04662366],
       [-0.91311213,  0.85425294, -1.62807293, -0.28957138],
       [-0.48150038, -0.85434409,  0.00672507,  0.78153558],
       [ 0.85597202,  0.3670469 , -0.51127563,  0.3380415 ],
       [ 1.22580031,  0.19685494, -0.44496695,  0.48545642]])

In [378]:
a = [1,2,3,4,5]

In [379]:
a.index(max(a))

4

In [380]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [419]:
np2 = np.array([1,2,3,9, 5,7])
np3 = np.array([4,5,6,5])

lent = (len(np2) - len(np3))

if(len(np3) !=len(np2)):
    np3 =  np.append(np3,np.ones(lent))

mul = np.array(np2*np3).sum()


In [416]:
mul

89.0

In [417]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [422]:
np1[np.isnan(np1)]

array([nan, nan])

In [427]:
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [ ]:
import matplotlib.pyplot as plt
#bar graph

